version: "3"
services:
  bot:
    restart: on-failure
    environment:
      - CONSUMER_KEY=${CONSUMER_KEY}
      - CONSUMER_SECRET=${CONSUMER_SECRET}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
    build: .
    volumes:
      - .:/bot
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    volumes:
      - ./data/db:/data