version: "3"
services:
  bot:
    restart: on-failure
    environment:
      - PORT=3001
    build: .
    volumes:
      - .:/bot
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    volumes:
      - ./data/db:/data/db